/**
 * Watermark text displayed as a decorative background on the hero section.
 * Extracted to keep the component files clean.
 */
export const WATERMARK_TEXT = `Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors, and the most patient of teachers. A reader lives a thousand lives before he dies. The man who never reads lives only one. Reading is to the mind what exercise is to the body. There is no friend as loyal as a book. A book is a dream that you hold in your hand. Once you learn to read, you will be forever free. The more that you read, the more things you will know. The more that you learn, the more places you'll go. Reading gives us someplace to go when we have to stay where we are. A room without books is like  a body without a soul. Velikonoční masakr byla tragická událost, ke které došlo na Velikonoční pondělí 22. dubna 1946 na severu tehdejšího Československa, ve Frýdlantském výběžku, mezi obcemi Lázně Libverda a Hejnice. Odpoledne toho dne vyrazila skupina dvou německých dívek a dvou chlapců k Jizerské chatě u Lázní Libverdy. Sledovala je parta pěti českých chlapců, ozbrojených pistolemi. Mezi oběma obcemi se německá skupina zastavila v boudě selské pískovny. Zde je pronásledovatelé překvapili a shromáždili.

Při předávání pistole mezi členy české party vyšel náhodný výstřel a v nastalém zmatku začal Zdeněk Mach do Němců bezhlavě pálit. Jedna dívka byla na místě mrtvá, druhá zraněná a jeden z německých chlapců v bezvědomí. Češi se po střelbě rozutekli, ale postupně se na místo vraceli. Zraněná Němka prosila o pomoc, Mach ji však zastřelil. Když se německý chlapec probral z bezvědomí, doplazil se do libverdského statku, odkud mu zavolali lékařskou pomoc a uvědomili hejnické strážníky. Ti ještě týž večer vyrazili zatknout Macha, který však při jejich příchodu spáchal sebevraždu.

Po soudním přelíčení dostal nejstarší z party jednoroční trest s podmínkou na pět let a zbylá trojice byla poslána do diagnostického ústavu. Československé úřady se obávaly nepokojů, přikázaly proto pohřeb pouze v úzkém rodinném kruhu a následně pozůstalou rodinu urychleně vystěhovaly do Německa.Velikonoční masakr byla tragická událost, ke které došlo na Velikonoční pondělí 22. dubna 1946 na severu tehdejšího Československa, ve Frýdlantském výběžku, mezi obcemi Lázně Libverda a Hejnice. Odpoledne toho dne vyrazila skupina dvou německých dívek a dvou chlapců k Jizerské chatě u Lázní Libverdy. Sledovala je parta pěti českých chlapců, ozbrojených pistolemi. Mezi oběma obcemi se německá skupina zastavila v boudě selské pískovny. Zde je pronásledovatelé překvapili a shromáždili.

Při předávání pistole mezi členy české party vyšel náhodný výstřel a v nastalém zmatku začal Zdeněk Mach do Němců bezhlavě pálit. Jedna dívka byla na místě mrtvá, druhá zraněná a jeden z německých chlapců v bezvědomí. Češi se po střelbě rozutekli, ale postupně se na místo vraceli. Zraněná Němka prosila o pomoc, Mach ji však zastřelil. Když se německý chlapec probral z bezvědomí, doplazil se do libverdského statku, odkud mu zavolali lékařskou pomoc a uvědomili hejnické strážníky. Ti ještě týž večer vyrazili zatknout Macha, který však při jejich příchodu spáchal sebevraždu.

Po soudním přelíčení dostal nejstarší z party jednoroční trest s podmínkou na pět let a zbylá trojice byla poslána do diagnostického ústavu. Československé úřady se obávaly nepokojů, přikázaly proto pohřeb pouze v úzkém rodinném kruhu a následně pozůstalou rodinu urychleně vystěhovaly do Německa.Velikonoční masakr byla tragická událost, ke které došlo na Velikonoční pondělí 22. dubna 1946 na severu tehdejšího Československa, ve Frýdlantském výběžku, mezi obcemi Lázně Libverda a Hejnice. Odpoledne toho dne vyrazila skupina dvou německých dívek a dvou chlapců k Jizerské chatě u Lázní Libverdy. Sledovala je parta pěti českých chlapců, ozbrojených pistolemi. Mezi oběma obcemi se německá skupina zastavila v boudě selské pískovny. Zde je pronásledovatelé překvapili a shromáždili.

Při předávání pistole mezi členy české party vyšel náhodný výstřel a v nastalém zmatku začal Zdeněk Mach do Němců bezhlavě pálit. Jedna dívka byla na místě mrtvá, druhá zraněná a jeden z německých chlapců v bezvědomí. Češi se po střelbě rozutekli, ale postupně se na místo vraceli. Zraněná Němka prosila o pomoc, Mach ji však zastřelil. Když se německý chlapec probral z bezvědomí, doplazil se do libverdského statku, odkud mu zavolali lékařskou pomoc a uvědomili hejnické strážníky. Ti ještě týž večer vyrazili zatknout Macha, který však při jejich příchodu spáchal sebevraždu.

Po soudním přelíčení dostal nejstarší z party jednoroční trest s podmínkou na pět let a zbylá trojice byla poslána do diagnostického ústavu. Československé úřady se obávaly nepokojů, přikázaly proto pohřeb pouze v úzkém rodinném kruhu a následně pozůstalou rodinu urychleně vystěhovaly do Německa.Velikonoční masakr byla tragická událost, ke které došlo na Velikonoční pondělí 22. dubna 1946 na severu tehdejšího Československa, ve Frýdlantském výběžku, mezi obcemi Lázně Libverda a Hejnice. Odpoledne toho dne vyrazila skupina dvou německých dívek a dvou chlapců k Jizerské chatě u Lázní Libverdy. Sledovala je parta pěti českých chlapců, ozbrojených pistolemi. Mezi oběma obcemi se německá skupina zastavila v boudě selské pískovny. Zde je pronásledovatelé překvapili a shromáždili.

Při předávání pistole mezi členy české party vyšel náhodný výstřel a v nastalém zmatku začal Zdeněk Mach do Němců bezhlavě pálit. Jedna dívka byla na místě mrtvá, druhá zraněná a jeden z německých chlapců v bezvědomí. Češi se po střelbě rozutekli, ale postupně se na místo vraceli. Zraněná Němka prosila o pomoc, Mach ji však zastřelil. Když se německý chlapec probral z bezvědomí, doplazil se do libverdského statku, odkud mu zavolali lékařskou pomoc a uvědomili hejnické strážníky. Ti ještě týž večer vyrazili zatknout Macha, který však při jejich příchodu spáchal sebevraždu.

Po soudním přelíčení dostal nejstarší z party jednoroční trest s podmínkou na pět let a zbylá trojice byla poslána do diagnostického ústavu. Československé úřady se obávaly nepokojů, přikázaly proto pohřeb pouze v úzkém rodinném kruhu a následně pozůstalou rodinu urychleně vystěhovaly do Německa.`;
